Use File System Access
chicory-pizza/chicory-data pull request #11
Opened 2022-03-10 09:51 UTC by chevreaux

Tested on Chrome & Firefox. When saving files, Chrome uses File System Access API to open a file picking window. Firefox just downloads like we're doing now.

As far as I can tell, there's no need for CustomFileInput anymore, but I left it in there in case I'm wrong.

2022-03-10 21:54 UTC, ngyikp commented
Thanks for the PR! There are a couple of infra issues that got uncovered such as updating package-lock.json to the new version (I ought to just update my Node and npm version...) and fixing the Jest test runner to [support ES6 modules](https://jestjs.io/docs/ecmascript-modules), I'm trying to fix those and hopefully get the CI to pass.

2022-03-10 22:52 UTC, chevreaux commented
At the moment I've just told Jest to ignore the browser-fs-access module.

2022-03-11 00:29 UTC, ngyikp requested changes
I updated the project to the latest versions including the new package lock, sorry for the rebase!

At first glance, it looks ok, I'm going to try testing on different browsers to ensure nothing is broken

2022-03-11 00:29 UTC, ngyikp commented on package.json
> +    "test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!browser-fs-access)/\""
I think adding a new Jest config at the end of package.json makes more sense
```js
  "jest": {
    "transformIgnorePatterns": [
      "/node_modules/(?!(browser-fs-access))/\"
    ]
  }
```

2022-03-11 00:29 UTC, ngyikp commented on src/header/DataSelector.js
> +				return console.error(err);
```suggestion
				console.error(err);
				alert('There was a problem saving the file.');
```

2022-03-11 00:29 UTC, ngyikp commented on src/header/DataSelector.js
> +				<button type="button" tabIndex={-1} onClick={openFile}>
`tabindex={-1}` was previously done due to how the custom file input is implemented, the real file input is overlayed on top and made invisible, while this button is fake, we don't want keyboard navigation to actually tab into this fake button.

Since we are now using the new module, this button is real now
```suggestion
				<button type="button" onClick={openFile}>
```

2022-03-11 00:29 UTC, ngyikp commented on src/terrainEditor/LevelTerrainEditorModal.js
> +		};
Why change the order? I sorta put `img.src` at the bottom to ensure the events are binded first

2022-03-11 00:29 UTC, ngyikp commented on src/terrainEditor/LevelTerrainEditorModal.js
> +				fileName: `Level_Geometry_${currentCoordinates[0]}_${currentCoordinates[1]}_${currentCoordinates[2]}`,
This file name is for human eyes, feel free to use spaces
```suggestion
				fileName: `Level terrain for ${currentCoordinates[0]}, ${currentCoordinates[1]}, ${currentCoordinates[2]}`,
```

2022-03-11 00:29 UTC, ngyikp commented on src/terrainEditor/LevelTerrainEditorModal.js
> +							<button type="button" tabIndex={-1} onClick={openFile}>
```suggestion
							<button type="button" onClick={openFile}>
```

2022-03-11 00:55 UTC, ngyikp commented
I tried the implementation and still see annoying save dialog every time I click the Save button, looking at Excalidraw, they save the file handle when doing `await fileSave()`

So something like this should work, I think:
```js
const saveFileHandleRef = useRef(null);

saveFileHandleRef.current = await fileSave(blob, options, saveFileHandleRef.current);
```

2022-03-11 01:40 UTC, chevreaux commented
We should be able to get the file handle when its opened so we never see the save dialog at all, if that's preferable.

2022-03-11 01:47 UTC, ngyikp approved these changes

2022-03-11 01:47 UTC, ngyikp commented
Checked on latest Chrome, the saved file handle ref works great and doesn't repeatedly prompt to save the file
Checked on Firefox and Safari, everything still works fine 👍

2022-03-11 01:47 UTC, merged

2022-03-11 01:52 UTC, ngyikp commented
> We should be able to get the file handle when its opened so we never see the save dialog at all, if that's preferable.

I do wonder about the UX of that, not sure do people expect that selecting level_data would mean immediately overwrite the existing file...