Edit Decorations
chicory-pizza/chicory-data pull request #24
Opened 2022-05-09 07:11 UTC by chevreaux

Decorations on the preview and in the sidebar. Sprites ready to go once this is in.

Essentially, any component that works with objects can now take and object or a deco. (I'm using 'Entity' to refer to objects and decos together.) I tried to do this by having a single prop with a union type (ex: Entity: GameObjectType | DecorationType). That would require a lot more work though. Instead:

- LevelPreviewEntities, SidebarEntityAdder and WorldDataContext reducer actions take in a string that tells them which type they are for.
- SidebarEntityList and SidebarEntityItem have a deco? and an obj? prop, and only receive one from their parent.

There is more code repetition than I would like, but I can't think of a better way. 

Probably the biggest issue right now is the Select menu for adding decorations. It's really laggy with 1700 entries.

2022-05-10 20:09 UTC, ngyikp requested changes

2022-05-10 20:09 UTC, ngyikp commented on src/levelEditor/sidebar/objectsList/SidebarObjectText.js
> +	obj: ?GameObjectType,
Not needed if SidebarEntityItem.js checks that the object is non-null
```suggestion
	obj: GameObjectType,
```

2022-05-10 20:09 UTC, ngyikp commented on src/levelEditor/types/EntityCategories.js
> +export const SPRITES: $ReadOnlyArray<SpriteType> = [
Split the sprites/game objects to their own files, at least to not ruin the Git blame history

2022-05-10 20:09 UTC, ngyikp commented on src/levelEditor/sidebar/properties/PropertyNumberInput.js
> +	step,
```suggestion
	step = 1,
```

2022-05-10 20:09 UTC, ngyikp commented on src/levelEditor/types/PlaceableType.js
> +};
Does this not work?
```suggestion
export type PlaceableType = {
	type: 'OBJECT',
	data: GameObjectEntityType,
} | {
	type: 'DECO',
	data: SpriteType,
};
```

2022-05-10 20:25 UTC, ngyikp commented on src/levelEditor/preview/LevelPreview.js
> -			{props.activeUiViews.includes('OBJECTS') &&
I fixed it in [62f418a](https://github.com/chicory-pizza/chicory-data/commit/62f418a3df8ef8d47f0e09945f318bb881edbb1d)

2022-05-11 20:44 UTC, chevreaux commented on .prettierignore
> +src/levelEditor/spriteData.json
I've written a script for UndertaleModTool that extracts the data for all sprites.

2022-05-13 08:00 UTC, chevreaux commented on src/levelEditor/types/PlaceableType.js
> +};
This causes SidebarEntityAdder to complain in a way I don't know how to fix.

2022-05-13 08:24 UTC, chevreaux commented on src/levelEditor/preview/LevelPreviewEntities.module.css
> +	background: rgb(85, 96, 255);
I'll use Luncheon purple instead.

2022-05-13 08:25 UTC, chevreaux commented on src/levelEditor/preview/LevelPreviewEntities.js
> +	if (props.type === 'OBJECT') {
Hah, I had something like this in an earlier version. I can make that change some time later.

2022-05-15 09:35 UTC, ngyikp commented on src/levelEditor/types/PlaceableType.js
> +};
Yeah: https://flow.org/en/docs/types/unions/#toc-disjoint-object-unions

2022-05-15 09:39 UTC, ngyikp commented on src/levelEditor/sidebar/objectsList/SidebarObjectText.js
> +	}
obj is never non-null, this is unneeded
```suggestion
```

2022-05-15 09:41 UTC, ngyikp commented on .prettierignore
> +src/levelEditor/spriteData.json
Can you share the script somewhere such as a repo or gist?

2022-05-15 10:09 UTC, ngyikp approved these changes
LGTM, basic functionality works well, let's fix any new issues on a new PR

2022-05-15 10:09 UTC, merged