Draw Sprites
chicory-pizza/chicory-data pull request #27
Opened 2022-05-16 05:37 UTC by chevreaux

Pull images from temple.chicory.pizza to draw sprites.
Also a few CSS changes to align stuff better.

2022-05-16 09:27 UTC, ngyikp requested changes
Sprites preview work nice 👍

Probably should show the sprite image preview when adding and mousing over the world, instead of just the text

Add REACT_APP_SPRITES_URL_PREFIX to `.env` as well

2022-05-16 09:27 UTC, ngyikp commented on src/levelEditor/preview/LevelPreviewEntities.js
> +				decoElement = <>{dec.spr}</>;
React fragment not needed here
```suggestion
				decoElement = dec.spr;
```

2022-05-16 09:27 UTC, ngyikp commented on src/levelEditor/preview/LevelPreviewEntities.js
> +						key={index}
When switching between levels, loading new images will 'lag' as browsers don't immediately unload the image
https://stackoverflow.com/a/61023057
```suggestion
						key={src}
```

2022-05-16 09:27 UTC, ngyikp commented on src/levelEditor/preview/LevelPreviewEntities.module.css
> +	z-index: 2;
Original in-game screenshot also shares the same z-index so if you have both decorations/in-game screenshot shown, you can't click the decos

Let's move `.item` to z-index 4 and decos can be at 3

2022-05-17 01:28 UTC, chevreaux commented on src/levelEditor/preview/LevelPreview.js
> +						transform: 'translate(-50%,-50%)',
Items with negative x or y shouldn't be a problem because the items are still drawn properly if they're offscreen.

2022-05-17 02:57 UTC, chevreaux commented
I've set the sprite image when adding a decoration to draw over everything else, but it'd be nice to have it reflect how it would actually show up in game.

2022-05-17 09:20 UTC, ngyikp approved these changes
Aw yeah
![pizza dance](https://user-images.githubusercontent.com/6135313/168777135-1ff3fd96-ab13-42a1-96fb-807f332c00c8.png)

2022-05-17 09:21 UTC, merged