Draggable objects and decos
chicory-pizza/chicory-data pull request #69
Opened 2023-04-03 03:50 UTC by PlasmaFlare

Working implementation for issue https://github.com/chicory-pizza/chicory-data/issues/37

- How it works:
   - Replace div that wraps around the object/deco with a `TransformDiv`
   - `TransformDiv` updates its own internal position when user drags the div around
   - When user stops dragging, `TransformDiv` emits event of updated position. `LevelInspector` picks up on the change and calls dispatch to update object/deco properties
- Note: Most of the code is designed in mind for supporting more transform operations in the future, such as scaling and rotating. But for now, moving is the only supported operation.

2023-04-03 10:38 UTC, ngyikp requested changes
Let's also show the move cursor when moving?

2023-04-03 10:38 UTC, ngyikp commented on src/levelEditor/preview/TransformDiv.jsx
> +	function transformReducer(
The reducer is probably overkill right now, but it makes sense when we want to add more functionality 👍 

Put the reducer function outside the component to be clearer

2023-04-03 10:38 UTC, ngyikp commented on src/levelEditor/preview/TransformDiv.jsx
> +	}, [
The `baseTransform` object is being reconstructed on every re-render, listing out each property just masks the problem

2023-04-03 10:38 UTC, ngyikp commented on src/levelEditor/preview/TransformDiv.jsx
> +export default (memo<Props>(TransformDiv): React$AbstractComponent<
memo is only useful if it's carefully optimized to reuse the same functions/objects on every re-render

Right now the components that are using `<TransformDiv>` aren't doing that, so memo will never work and waste CPU, let's remove it

2023-04-03 10:38 UTC, ngyikp commented on src/levelEditor/preview/TransformDiv.jsx
> +	| {type: null};
This null action shouldn't be needed?

2023-04-03 10:38 UTC, ngyikp commented on src/levelEditor/preview/TransformDiv.jsx
> +type TransformAction = 'move';
```suggestion
type TransformAction = 'MOVE';
```

2023-04-03 10:38 UTC, ngyikp commented on src/levelEditor/preview/TransformDiv.jsx
> +	const [transformAction, setTransformAction] =
To be clearer
```suggestion
	const [currentTransformAction, setCurrentTransformAction] =
```

2023-04-03 14:44 UTC, PlasmaFlare commented on src/levelEditor/preview/TransformDiv.jsx
> +	function transformReducer(
By "outside", you mean move the function definition to be outside the `TransformDiv` function?

2023-04-03 18:20 UTC, ngyikp commented on src/levelEditor/preview/TransformDiv.jsx
> +	function transformReducer(
Yes

2023-04-03 23:10 UTC, PlasmaFlare commented on src/levelEditor/preview/TransformDiv.jsx
> +	}, [
That still doesn't tell me what I should do.

2023-04-04 01:07 UTC, ngyikp commented on src/levelEditor/preview/LevelPreviewObjects.jsx
> +				baseTransform={{x: obj.x, y: obj.y}}
This breaks rotation/scaling for objCustomDog, but I'll fix them later as that's a rarely used feature

2023-04-04 01:07 UTC, ngyikp approved these changes

2023-04-04 01:07 UTC, merged